//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Giris.cs
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Uye
    {
        public int ID { get; set; }
        public string UyeAdSoyad { get; set; }
        public Nullable<System.DateTime> KayitTarihi { get; set; }
        public string MailAdresi { get; set; }
        public Nullable<int> Telefon { get; set; }
        public string Adres { get; set; }
        public Nullable<System.DateTime> DogumTarihi { get; set; }
    }
}
