//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Giris.cs
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_KulKayit
    {
        public int Kul_ID { get; set; }
        public string KullaniciAdi { get; set; }
        public string Sifre { get; set; }
        public Nullable<System.DateTime> KayitTarihi { get; set; }
        public Nullable<int> YetkiID { get; set; }
    }
}
