//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Giris.cs
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Haberver
    {
        public int ID { get; set; }
        public Nullable<int> KitapID { get; set; }
        public Nullable<int> UyeID { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
    }
}
